// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErlNebxSBgCGN9yWjvM8wHXcVD_ojBHs',
    appId: '1:425317413761:web:8007aee497fcc61eb76e80',
    messagingSenderId: '425317413761',
    projectId: 'teach-to-reach',
    authDomain: 'teach-to-reach.firebaseapp.com',
    storageBucket: 'teach-to-reach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukyNtkrLb6qMOvfNtgGlm23le6mqNIpU',
    appId: '1:425317413761:ios:ae73cd10211a6e90b76e80',
    messagingSenderId: '425317413761',
    projectId: 'teach-to-reach',
    storageBucket: 'teach-to-reach.firebasestorage.app',
    iosClientId: '425317413761-tgraenrluhpvbmtl3ktvgco1647sk60n.apps.googleusercontent.com',
    iosBundleId: 'com.mancavegaming.teachToReach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAukyNtkrLb6qMOvfNtgGlm23le6mqNIpU',
    appId: '1:425317413761:ios:ae73cd10211a6e90b76e80',
    messagingSenderId: '425317413761',
    projectId: 'teach-to-reach',
    storageBucket: 'teach-to-reach.firebasestorage.app',
    iosClientId: '425317413761-tgraenrluhpvbmtl3ktvgco1647sk60n.apps.googleusercontent.com',
    iosBundleId: 'com.mancavegaming.teachToReach',
  );
}
